# Generated by Django 5.2.5 on 2025-09-19 09:25

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'jpg', 'png'])], verbose_name='document'),
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='person',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
